#include "proto/core/graphics/common.hh"

#include "proto/core/graphics/ShaderProgram.hh"
#include "proto/core/graphics/TextureInterface.hh"
#include "proto/core/graphics/Texture2D.hh"
#include "proto/core/graphics/Cubemap.hh"
#include "proto/core/graphics/Vertex.hh"
#include "proto/core/graphics/Mesh.hh"
#include "proto/core/graphics/Material.hh"
#include "proto/core/graphics/Renderbuffer.hh"
#include "proto/core/graphics/Camera.hh"
#include "proto/core/graphics/Framebuffer.hh"

#include "proto/core/graphics/gl.hh"
#include "proto/core/graphics/primitives.hh"
#include "proto/core/graphics/rendering.hh"
//#include "text.hh"
